server:
  port: 8666

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/admin/**, /api/v1/user/**, /api/v1/auth/**
        
