server:
  port: 8081

eureka:
  server:
    eviction-interval-timer-in-ms: 60000  # Adjust this value as needed (default is 60,000 ms)
    renewalThresholdUpdateIntervalMs: 5000  # Adjust this value as needed (default is 5,000 ms)
    response-cache-update-interval-ms: 30000  # Adjust this value as needed (default is 30,000 ms)
    useReadOnlyResponseCache: false  # Set to false to disable read-only response cache

  instance:
    lease-renewal-interval-in-seconds: 30  # Adjust this value as needed (default is 30 seconds)
    lease-expiration-duration-in-seconds: 90 # Adjust this value as needed (default is 90 seconds)
    
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/db_ehr
    username: root
    password: Palden1923
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
